[package]
name = "intranet_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
gethostname = "0.5.0"
sysinfo = "0.33.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
